- src: geerlingguy.repo-epel
- src: weareinteractive.nginx
- src: geerlingguy.nginx
- src: joshualund.golang
- name: weareinteractive.nginx
  src: https://github.com/rustx/weareinteractive.nginx
  version: tc-changes
